"""Cross-platform git-hook launcher (R40)."""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

from _sw import interpreter, proc
from _sw.cli import build_parser, run_module_main


def repo_root_from(start: Path) -> Path:
    env = os.environ.get("SW_REPO_ROOT", "").strip()
    if env:
        return Path(env)
    return start


def hook_entry_content(python_args: list[str], target: Path) -> str:
    exe = " ".join(python_args)
    return f"#!{exe}\n# Generated by Shipwright hook launcher (R40)\nimport runpy\nrunpy.run_path({str(target)!r}, run_name='__main__')\n"


def windows_cmd_content(python_args: list[str], launcher_py: Path) -> str:
    cmd = " ".join(python_args)
    return (
        "@echo off\r\n"
        "setlocal\r\n"
        f'"{cmd}" "{launcher_py}" %*\r\n'
        "exit /b %ERRORLEVEL%\r\n"
    )


def install_hook(
    hooks_dir: Path,
    hook_name: str,
    target_script: Path,
    *,
    repo_root: Path | None = None,
) -> None:
    """Install a hook entry + Windows shim into *hooks_dir*."""
    repo_root = repo_root or repo_root_from(hooks_dir)
    hooks_dir.mkdir(parents=True, exist_ok=True)
    result = interpreter.probe()
    launcher_py = Path(__file__).resolve()
    entry = hooks_dir / hook_name
    entry.write_text(
        hook_entry_content(result.executable, target_script.resolve()),
        encoding="utf-8",
        newline="\n",
    )
    entry.chmod(entry.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    cmd_path = hooks_dir / f"{hook_name}.cmd"
    cmd_path.write_text(
        windows_cmd_content(result.executable, launcher_py),
        encoding="utf-8",
        newline="\r\n",
    )


def dispatch(target: Path, argv: list[str]) -> int:
    result = interpreter.probe()
    completed = proc.run([*result.executable, str(target), *argv])
    if completed.stdout:
        sys.stdout.write(completed.stdout)
    if completed.stderr:
        sys.stderr.write(completed.stderr)
    return completed.returncode


def main(argv: list[str] | None = None) -> int:
    parser = build_parser(
        prog="hook-launcher",
        description="Cross-platform git hook launcher shim (R40).",
    )
    parser.add_argument("target", help="Hook Python script to execute")
    parser.add_argument("hook_args", nargs="...", help="Forwarded hook args")
    args = parser.parse_args(argv)
    target = Path(args.target)
    if not target.is_file():
        print(f"hook target not found: {target}", file=sys.stderr)
        return 2
    return dispatch(target.resolve(), list(args.hook_args))


if __name__ == "__main__":
    run_module_main(lambda: main())
