"""Capability-driven emitter base for Shipwright platform trees."""

from __future__ import annotations

import json
import os
import re
import shutil
import threading
from abc import ABC, abstractmethod
from contextlib import contextmanager
from pathlib import Path

EMITTABLE_DIRS = ("commands", "skills", "rules", "agents", "providers", "communication")

EXCLUDE_DIR_NAMES = {"__pycache__", "test", "tests", "unit_tests", ".git", "node_modules"}
DEV_TEST_SCRIPT_DIRS = frozenset({"test", "tests", "unit_tests"})
DEV_ONLY_SCRIPT_RELPATHS = (
    "scripts/core_content_sync.py",
    "scripts/snapshot-tree.sh",
    "scripts/snapshot-tree.py",
    "scripts/model-routing-check.sh",
    "scripts/model-routing-check.py",
)

# planning_store.py is regenerated by planning_shim_gen with path-depth-specific
# _REPO_ROOT_DEPTH (core=2, dist=3); do not verbatim-copy the core shim into dist.
EXCLUDE_REL_PATHS = frozenset(
    {"scripts/install.sh", "scripts/planning_store.py", *DEV_ONLY_SCRIPT_RELPATHS}
)

SW_REFERENCE_CLOSED_EMIT = (
    "config.schema.json",
    "planning-unit.schema.json",
    "inflight-signal.schema.json",
    "inflight-tuple.schema.json",
    "layout.md",
    "workflow.config.example.json",
    "communication-routing.defaults.json",
    "model-routing.defaults.json",
    "verify-presets.json",
    "harness-roots-manifest.json",
    "capability-index.json",
    "capability-manifest.schema.json",
    "signal-context.schema.json",
    "kernel-classification.json",
    "kernel-classification.md",
    "guidelines.schema.json",
    "guidelines.json",
    "guidelines.md",
    # Hook trust + adapter registration (PRD 071) — required in plugin installs
    "memory-provider-catalog.json",
)
EXCLUDE_SUFFIXES = (".pyc",)

CURSOR_PLUGIN_ROOT = "${CURSOR_PLUGIN_ROOT}"
CLAUDE_PLUGIN_ROOT = "${CLAUDE_PLUGIN_ROOT}"
CURSOR_FALLBACK_RE = re.compile(
    r"\$HOME/\.cursor/plugins/local/shipwright"
)


class EmitterError(Exception):
    """Raised when generation cannot satisfy the platform descriptor."""


class HostConventionWriteForbidden(EmitterError):
    """Raised when workflow logic attempts a direct write to a host-convention path."""


# Host-required integration surfaces only — not Shipwright runtime state under legacy
# `.cursor/sw-*` (relocated to `.shipwright/` via shipwright_paths).
HOST_CONVENTION_PREFIXES: tuple[str, ...] = (
    ".cursor/rules/",
    ".cursor/hooks/hooks.json",
    ".cursor-plugin/",
    ".claude/",
)

_emitter_write_guard = threading.local()


def _emitter_writes_allowed() -> bool:
    return bool(getattr(_emitter_write_guard, "allowed", False))


@contextmanager
def emitter_write_context():
    """Allow host-convention writes only while platform emitters are emitting."""
    previous = getattr(_emitter_write_guard, "allowed", False)
    _emitter_write_guard.allowed = True
    try:
        yield
    finally:
        _emitter_write_guard.allowed = previous


def refuse_workflow_write_to_host_convention(target: Path, repo_root: Path) -> None:
    """Refuse direct workflow writes to host-convention directories (PRD 342 R10)."""
    if _emitter_writes_allowed():
        return
    root = repo_root.resolve()
    try:
        rel = target.resolve().relative_to(root).as_posix()
    except ValueError as exc:
        raise HostConventionWriteForbidden(
            f"host-convention write refused: {target} is outside repo root {root}"
        ) from exc
    for prefix in HOST_CONVENTION_PREFIXES:
        normalized = prefix.rstrip("/")
        if rel == normalized or rel.startswith(prefix):
            raise HostConventionWriteForbidden(
                "host-convention paths receive host-required files only through platform "
                f"emitters and descriptors; refused workflow write to {rel!r} "
                f"(allowed prefixes: {list(HOST_CONVENTION_PREFIXES)})"
            )


def write_host_convention_file(
    repo_root: Path, rel_path: str, content: str | bytes, *, mode: int | None = None
) -> Path:
    """Write a host-required file from an emitter context only."""
    if not _emitter_writes_allowed():
        raise HostConventionWriteForbidden(
            "write_host_convention_file requires emitter_write_context()"
        )
    dest = (repo_root / rel_path).resolve()
    refuse_workflow_write_to_host_convention(dest, repo_root)
    dest.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, str):
        dest.write_text(content, encoding="utf-8")
    else:
        dest.write_bytes(content)
    if mode is not None:
        dest.chmod(mode)
    return dest


def read_version(repo_root: Path) -> str:
    """Read the bare semver string from repo-root version.txt."""
    path = repo_root / "version.txt"
    if not path.is_file():
        raise EmitterError(f"missing version source: {path}")
    version = path.read_text(encoding="utf-8").strip()
    if not version:
        raise EmitterError(f"empty version source: {path}")
    return version


class EmitterBase(ABC):
    """Copy emittable core/ content and apply platform-specific wiring."""

    platform_id: str

    def __init__(self, descriptor: dict) -> None:
        self.descriptor = descriptor
        self.platform_id = str(descriptor.get("platform", ""))

    def validate_descriptor(self) -> None:
        """Subclasses enforce supported capability flags (R4)."""
        return

    def emit(self, core_root: Path, repo_root: Path, dest: Path) -> None:
        """Write the full platform tree to dest."""
        with emitter_write_context():
            self._emit_impl(core_root, repo_root, dest)

    @abstractmethod
    def _emit_impl(self, core_root: Path, repo_root: Path, dest: Path) -> None:
        """Platform-specific emit implementation."""

    def emit_zipapp_runtime(self, repo_root: Path, dest: Path) -> None:
        """Build shipwright.pyz and install the per-host thin shim (PRD 091 R3)."""
        import sys

        scripts_dir = repo_root / "scripts"
        if str(scripts_dir) not in sys.path:
            sys.path.insert(0, str(scripts_dir))
        from build_zipapp import build_archive  # noqa: WPS433

        build_archive(repo_root, dest)
        shim_dir = dest / "scripts"
        shim_dir.mkdir(parents=True, exist_ok=True)
        shim_path = shim_dir / "sw-run.py"
        shim_path.write_text(self.render_zipapp_shim(), encoding="utf-8")
        shim_path.chmod(0o755)

    def render_zipapp_shim(self) -> str:
        env_name = self.plugin_root_env_name()
        return f'''#!/usr/bin/env python3
"""Thin host shim — invoke Shipwright scripts via the versioned zipapp."""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

_PLUGIN_ROOT_ENV = "{env_name}"


def _resolve_pyz(plugin_root: Path) -> Path:
    stable = plugin_root / "shipwright.pyz"
    if stable.is_file():
        return stable
    candidates = sorted(plugin_root.glob("shipwright-*.pyz"))
    if not candidates:
        raise FileNotFoundError(f"no shipwright.pyz under {{plugin_root}}")
    return candidates[-1]


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: sw-run.py <script.py> [args...]", file=sys.stderr)
        return 2
    plugin_root = Path(
        os.environ.get(_PLUGIN_ROOT_ENV, Path(__file__).resolve().parent.parent)
    )
    pyz = _resolve_pyz(plugin_root)
    env = os.environ.copy()
    env.setdefault(_PLUGIN_ROOT_ENV, str(plugin_root))
    cmd = [sys.executable, str(pyz), *sys.argv[1:]]
    return subprocess.call(cmd, env=env)


if __name__ == "__main__":
    raise SystemExit(main())
'''

    def copy_emittable_content(self, core_root: Path, dest: Path) -> list[str]:
        """Copy verbatim core subtrees; return relative paths written."""
        written: list[str] = []
        for dirname in EMITTABLE_DIRS:
            src = core_root / dirname
            if not src.is_dir():
                continue
            for path in sorted(src.rglob("*")):
                if not path.is_file():
                    continue
                rel = path.relative_to(src)
                parts = rel.parts
                if any(p in EXCLUDE_DIR_NAMES for p in parts):
                    continue
                out_rel = f"{dirname}/{rel.as_posix()}"
                if out_rel in EXCLUDE_REL_PATHS:
                    continue
                if path.suffix in EXCLUDE_SUFFIXES:
                    continue
                if path.suffix == ".sh" and dirname == "providers":
                    py_sibling = path.with_suffix(".py")
                    if py_sibling.is_file():
                        continue
                if dirname == "scripts" and parts and parts[0] in DEV_TEST_SCRIPT_DIRS:
                    continue
                out_path = dest / out_rel
                out_path.parent.mkdir(parents=True, exist_ok=True)
                content = path.read_bytes()
                content = self.transform_body(content, out_rel)
                out_path.write_bytes(content)
                written.append(out_rel)
        return written

    def transform_body(self, content: bytes, _rel_path: str) -> bytes:
        text = content.decode("utf-8")
        text = self.substitute_plugin_root_env(text)
        return text.encode("utf-8")

    def copy_closed_sw_reference(self, core_root: Path, dest: Path) -> None:
        """Emit the closed sw-reference set for user installs (PRD 018 R12/TR8)."""
        ref_src = core_root / "sw-reference"
        if not ref_src.is_dir():
            return
        ref_dir = dest / "core" / "sw-reference"
        ref_dir.mkdir(parents=True, exist_ok=True)
        for name in SW_REFERENCE_CLOSED_EMIT:
            src = ref_src / name
            if src.is_file():
                shutil.copy2(src, ref_dir / name)

    def substitute_plugin_root_env(self, text: str) -> str:
        target = self.plugin_root_env_name()
        if target == "CURSOR_PLUGIN_ROOT":
            return text
        text = re.sub(
            r"\$\{CURSOR_PLUGIN_ROOT(:-[^}]+)?\}",
            lambda m: f"${{{target}{m.group(1) or ''}}}",
            text,
        )
        text = CURSOR_FALLBACK_RE.sub(
            "$HOME/.claude/plugins/local/shipwright",
            text,
        )
        return text

    @abstractmethod
    def plugin_root_env_name(self) -> str:
        """Env var name for plugin root in emitted bodies."""

    @staticmethod
    def load_descriptor(path: Path) -> dict:
        return json.loads(path.read_text(encoding="utf-8"))


def ensure_clean_dir(path: Path) -> None:
    if not path.exists():
        path.mkdir(parents=True, exist_ok=True)
        return

    def _on_rm_error(func, p: str, exc_info: object) -> None:
        import stat

        if not os.access(p, os.W_OK):
            os.chmod(p, stat.S_IWUSR | stat.S_IRUSR | stat.S_IXUSR)
            func(p)
        else:
            raise exc_info[1]  # type: ignore[index]

    trash = path.parent / f".{path.name}.delete.{os.getpid()}"
    suffix = 0
    while trash.exists():
        suffix += 1
        trash = path.parent / f".{path.name}.delete.{os.getpid()}.{suffix}"
    path.rename(trash)
    shutil.rmtree(trash, onerror=_on_rm_error, ignore_errors=True)
    path.mkdir(parents=True, exist_ok=True)
