"""Planning domain package (PRD 082 phase 11 / R27)."""
from __future__ import annotations

from .identity import (
    BARE_INTEGER_UNIT_ID,
    DECISION_ARTIFACT_TYPE,
    DECISION_GRAPH_FILENAME,
    DECISION_GRAPH_UNIT_SUFFIX,
    DECISION_ISSUE_TYPE_LABEL,
    LEGACY_UNIT_MAP_PATH,
    NATIVE_UNIT_ID_PATTERN,
    NATIVE_UNIT_ID_PREFIX,
    PROJECT_KEY_PATTERN,
    PROJECT_KEY_REGISTRY,
    decision_graph_unit_id,
    decision_graph_virtual_body_path,
    decision_record_virtual_body_path,
    format_native_unit_id,
    is_bare_integer_unit_id,
    is_decision_graph_body_path,
    is_namespaced_native_unit_id,
    load_legacy_unit_map,
    load_project_key_registry,
    native_unit_id_prefix,
    register_legacy_unit_mapping,
    reject_bare_integer_unit_id,
    resolve_decision_put_path,
    resolve_legacy_unit_id,
    reverse_resolve_legacy_unit_id,
    resolve_store_location,
    save_legacy_unit_map,
    store_location_fingerprint,
    unit_id_lookup_candidates,
    validate_project_key,
)
from .migrations import ISSUES_MIGRATION_HOOKS, ORPHAN_MIGRATED_LABEL, migrate_orphan_phase_issues
from .model import (
    MATERIALIZE_MISSING_FROZEN_BODY,
    PlanningUnit,
    StoreResult,
    materialize_missing_result,
)
from .repository import PlanningStoreBackend

__all__ = [
    "BARE_INTEGER_UNIT_ID",
    "DECISION_ARTIFACT_TYPE",
    "DECISION_GRAPH_FILENAME",
    "DECISION_GRAPH_UNIT_SUFFIX",
    "DECISION_ISSUE_TYPE_LABEL",
    "ISSUES_MIGRATION_HOOKS",
    "LEGACY_UNIT_MAP_PATH",
    "MATERIALIZE_MISSING_FROZEN_BODY",
    "NATIVE_UNIT_ID_PATTERN",
    "NATIVE_UNIT_ID_PREFIX",
    "ORPHAN_MIGRATED_LABEL",
    "PROJECT_KEY_PATTERN",
    "PROJECT_KEY_REGISTRY",
    "PlanningStoreBackend",
    "PlanningUnit",
    "StoreResult",
    "decision_graph_unit_id",
    "decision_graph_virtual_body_path",
    "decision_record_virtual_body_path",
    "format_native_unit_id",
    "is_bare_integer_unit_id",
    "is_decision_graph_body_path",
    "is_namespaced_native_unit_id",
    "load_legacy_unit_map",
    "load_project_key_registry",
    "materialize_missing_result",
    "migrate_orphan_phase_issues",
    "native_unit_id_prefix",
    "register_legacy_unit_mapping",
    "reject_bare_integer_unit_id",
    "resolve_decision_put_path",
    "resolve_legacy_unit_id",
    "reverse_resolve_legacy_unit_id",
    "resolve_store_location",
    "save_legacy_unit_map",
    "store_location_fingerprint",
    "unit_id_lookup_candidates",
    "validate_project_key",
]
