#!/usr/bin/env python3
"""Generate .github/workflows/pr-test-plan-ci.yml from pr-test-plan.manifest.json (PRD 016 R1–R3)."""
from __future__ import annotations
import sys
from pathlib import Path
SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
from _sw.cli import run_module_main

def main(argv: list[str] | None = None) -> int:
    import json, sys
    from pathlib import Path

    from ci_shard_lib import group_fixtures_for_ci

    manifest_path, out_path, root = sys.argv[1], Path(sys.argv[2]), sys.argv[3]
    data = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    fixtures = data.get("fixtures") or []
    jobs = group_fixtures_for_ci(fixtures)

    lines = [
        "# Generated by scripts/generate-pr-test-plan-ci-workflow.py — do not edit by hand.",
        f"# Source: {Path(manifest_path).relative_to(root) if Path(manifest_path).is_relative_to(root) else manifest_path}",
        "name: PR test-plan (FEAT)",
        "",
        "on:",
        "  pull_request:",
        "",
        "permissions:",
        "  contents: read",
        "",
        "jobs:",
    ]

    for job in jobs:
        job_id = job["ciJobName"]
        classification = job.get("classification", "required")
        lines.append(f"  {job_id}:")
        lines.append(f"    name: {job_id}")
        lines.append("    runs-on: ubuntu-latest")
        if classification == "advisory":
            lines.append("    continue-on-error: true")
        lines.append("    steps:")
        lines.append("      - uses: actions/checkout@v4")
        lines.append("      - uses: actions/setup-python@v5")
        lines.append("        with:")
        lines.append('          python-version: "3.12"')
        suite_ids = job.get("suiteIds") or [entry["id"] for entry in job.get("entries") or []]
        label = ", ".join(suite_ids) if len(suite_ids) > 1 else str(suite_ids[0])
        lines.append(f"      - name: Run {label}")
        lines.append(f"        run: {job['command']}")
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(jobs)} jobs from {len(fixtures)} fixtures)")
    return 0

if __name__ == "__main__":
    run_module_main(main)
