#!/usr/bin/env bash
# Generate .github/workflows/pr-test-plan-ci.yml from pr-test-plan.manifest.json (PRD 016 R1–R3).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="${PR_TEST_PLAN_MANIFEST:-$ROOT/core/sw-reference/pr-test-plan.manifest.json}"
OUT="${1:-$ROOT/.github/workflows/pr-test-plan-ci.yml}"

if [[ ! -f "$MANIFEST" ]]; then
  echo "generate-pr-test-plan-ci-workflow: missing manifest: $MANIFEST" >&2
  exit 1
fi

python3 - "$MANIFEST" "$OUT" "$ROOT" <<'PY'
import json, sys
from pathlib import Path

manifest_path, out_path, root = sys.argv[1], Path(sys.argv[2]), sys.argv[3]
data = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
fixtures = data.get("fixtures") or []

lines = [
    "# Generated by scripts/generate-pr-test-plan-ci-workflow.sh — do not edit by hand.",
    f"# Source: {Path(manifest_path).relative_to(root) if Path(manifest_path).is_relative_to(root) else manifest_path}",
    "name: PR test-plan (FEAT)",
    "",
    "on:",
    "  pull_request:",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
]

for entry in fixtures:
    job_id = entry["ciJobName"]
    script = entry["script"]
    args = entry.get("args") or []
    classification = entry.get("classification", "required")
    cmd = "bash " + script + (" " + " ".join(args) if args else "")
    lines.append(f"  {job_id}:")
    lines.append(f"    name: {job_id}")
    lines.append("    runs-on: ubuntu-latest")
    if classification == "advisory":
        lines.append("    continue-on-error: true")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v4")
    lines.append("      - uses: actions/setup-python@v5")
    lines.append("        with:")
    lines.append('          python-version: "3.12"')
    lines.append(f"      - name: Run {entry['id']}")
    lines.append(f"        run: {cmd}")
    lines.append("")

out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {out_path} ({len(fixtures)} jobs)")
PY
