#!/usr/bin/env python3
"""Support matrix generator from timestamped conformance records (PRD 349 R46–R48).

Reads tested capability record JSON files and emits a host×surface×capability matrix.
Records lacking ``tested_at`` are rejected (fail-closed, non-zero exit).
CLI surface evidence never propagates to desktop (R48).
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

LEVELS: tuple[str, ...] = (
    "generated",
    "loads",
    "passes",
    "controls_verified",
)
LEVEL_RANK = {name: idx for idx, name in enumerate(LEVELS)}
SURFACES = frozenset({"cli", "desktop", "cloud"})


class MatrixGeneratorError(Exception):
    """Fail-closed generator error."""


@dataclass(frozen=True)
class ConformanceRecord:
    host: str
    surface: str
    host_version: str
    capability: str
    level: str
    tested_at: str
    source: str


@dataclass(frozen=True)
class MatrixCell:
    host: str
    surface: str
    host_version: str
    capability: str
    level: str
    tested_at: str


def _parse_tested_at(value: Any, source: str) -> str:
    if value is None or (isinstance(value, str) and not value.strip()):
        raise MatrixGeneratorError(f"record missing tested_at: {source}")
    text = str(value).strip()
    # Accept Z-suffix ISO-8601; reject empty / non-parseable.
    normalized = text.replace("Z", "+00:00") if text.endswith("Z") else text
    try:
        datetime.fromisoformat(normalized)
    except ValueError as exc:
        raise MatrixGeneratorError(f"invalid tested_at in {source}: {text}") from exc
    return text


def load_record(path: Path) -> ConformanceRecord:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise MatrixGeneratorError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(raw, dict):
        raise MatrixGeneratorError(f"record must be object: {path}")
    tested_at = _parse_tested_at(raw.get("tested_at"), str(path))
    host = str(raw.get("host") or "").strip()
    surface = str(raw.get("surface") or "").strip()
    host_version = str(raw.get("host_version") or "").strip()
    capability = str(raw.get("capability") or "").strip()
    level = str(raw.get("level") or "").strip()
    if not host or not surface or not host_version or not capability or not level:
        raise MatrixGeneratorError(
            f"record missing required fields (host/surface/host_version/capability/level): {path}"
        )
    if surface not in SURFACES:
        raise MatrixGeneratorError(f"unsupported surface {surface!r} in {path}")
    if level not in LEVEL_RANK:
        raise MatrixGeneratorError(f"unsupported level {level!r} in {path}")
    return ConformanceRecord(
        host=host,
        surface=surface,
        host_version=host_version,
        capability=capability,
        level=level,
        tested_at=tested_at,
        source=str(path),
    )


def load_records(records_dir: Path) -> list[ConformanceRecord]:
    if not records_dir.is_dir():
        raise MatrixGeneratorError(f"records directory not found: {records_dir}")
    paths = sorted(records_dir.glob("*.json"))
    if not paths:
        raise MatrixGeneratorError(f"no conformance records in {records_dir}")
    return [load_record(path) for path in paths]


def build_matrix(records: Iterable[ConformanceRecord]) -> list[MatrixCell]:
    """Collapse records to one cell per host×surface×capability×host_version.

    Cell level is the **highest** verified level present for that key (TS9).
    Surfaces are independent — CLI evidence never fills a desktop cell (R48).
    """
    best: dict[tuple[str, str, str, str], ConformanceRecord] = {}
    for record in records:
        key = (record.host, record.surface, record.host_version, record.capability)
        current = best.get(key)
        if current is None or LEVEL_RANK[record.level] > LEVEL_RANK[current.level]:
            best[key] = record
    cells = [
        MatrixCell(
            host=rec.host,
            surface=rec.surface,
            host_version=rec.host_version,
            capability=rec.capability,
            level=rec.level,
            tested_at=rec.tested_at,
        )
        for rec in best.values()
    ]
    cells.sort(key=lambda c: (c.host, c.surface, c.host_version, c.capability))
    return cells


def matrix_to_json(cells: list[MatrixCell]) -> dict[str, Any]:
    return {
        "generated_by": "scripts/matrix_generator.py",
        "levels": list(LEVELS),
        "cells": [asdict(cell) for cell in cells],
    }


def matrix_to_markdown(cells: list[MatrixCell]) -> str:
    lines = [
        "<!-- Generated by scripts/matrix_generator.py — do not edit by hand -->",
        "",
        "# Platform support matrix",
        "",
        "Generated exclusively from timestamped conformance records (`tested_at` required).",
        "CLI evidence does **not** imply desktop support (R48).",
        "",
        "| Host | Surface | Host version | Capability | Level | Tested at |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for cell in cells:
        lines.append(
            f"| {cell.host} | {cell.surface} | {cell.host_version} | "
            f"{cell.capability} | {cell.level} | {cell.tested_at} |"
        )
    lines.append("")
    lines.append("## Level legend")
    lines.append("")
    lines.append("| Level | Meaning |")
    lines.append("| --- | --- |")
    lines.append("| `generated` | Adapter artifact emitted |")
    lines.append("| `loads` | Host accepted the artifact |")
    lines.append("| `passes` | Workflow executed end-to-end |")
    lines.append(
        "| `controls_verified` | Hook blocking, dispatch binding, and memory validation confirmed |"
    )
    lines.append("")
    return "\n".join(lines)


def default_records_dir(repo_root: Path) -> Path:
    return repo_root / "core" / "schemas" / "capabilities" / "conformance"


def default_descriptors_dir(repo_root: Path) -> Path:
    return repo_root / "core" / "schemas" / "capabilities"


# Open questions still unresolved at phase-5 publish (R49).
UNRESOLVED_OPEN_QUESTIONS: tuple[tuple[str, str], ...] = (
    (
        "OQ-1",
        "Authoritative host version string when multiple conformance runs disagree — "
        "use newest tested_at row until pin policy is decided.",
    ),
    (
        "OQ-2",
        "Codex desktop surface requires independent conformance; CLI tested evidence "
        "must not be read as desktop support (R48).",
    ),
    (
        "OQ-3",
        "Cloud surface rollout timeline for Codex/OpenCode remains unset; cloud cells "
        "stay unsupported until independently tested.",
    ),
)


def collect_known_gaps(descriptors_dir: Path) -> list[dict[str, Any]]:
    """Collect unsupported / non-empty known_gaps rows from capability descriptors."""
    rows: list[dict[str, Any]] = []
    for path in sorted(descriptors_dir.glob("*.json")):
        if path.name.endswith(".schema.json") or path.name == "capability.schema.json":
            continue
        payload = json.loads(path.read_text(encoding="utf-8"))
        entries = payload if isinstance(payload, list) else [payload]
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            host = str(entry.get("host") or "")
            surface = str(entry.get("surface") or "")
            version = str(entry.get("version_range") or entry.get("host_version") or "")
            caps = entry.get("capabilities") or {}
            if not isinstance(caps, dict):
                continue
            for capability, detail in caps.items():
                if not isinstance(detail, dict):
                    continue
                mode = str(detail.get("implementation_mode") or "")
                gaps = detail.get("known_gaps") or []
                if not isinstance(gaps, list):
                    gaps = [str(gaps)]
                if mode != "unsupported" and not gaps:
                    continue
                rows.append(
                    {
                        "host": host,
                        "surface": surface,
                        "version": version,
                        "capability": capability,
                        "implementation_mode": mode,
                        "known_gaps": [str(g) for g in gaps],
                        "workaround_or_timeline": (
                            "unsupported on this host×surface — no adapter path until "
                            "independently tested"
                            if mode == "unsupported"
                            else "; ".join(str(g) for g in gaps)
                        ),
                        "oq_flags": (
                            ["OQ-2"]
                            if host == "codex" and surface == "desktop"
                            else (["OQ-3"] if surface == "cloud" else [])
                        ),
                    }
                )
    rows.sort(key=lambda r: (r["host"], r["surface"], r["capability"]))
    return rows


def known_gaps_to_markdown(rows: list[dict[str, Any]]) -> str:
    lines = [
        "<!-- Generated by scripts/matrix_generator.py — do not edit by hand -->",
        "",
        "# Known gaps",
        "",
        "Every capability with `implementation_mode: unsupported` or a non-empty "
        "`known_gaps` list, derived from `core/schemas/capabilities/*.json` (R49).",
        "",
        "## Open questions (unresolved at publish)",
        "",
    ]
    for oq_id, text in UNRESOLVED_OPEN_QUESTIONS:
        lines.append(f"- **{oq_id} (unresolved):** {text}")
    lines.extend(
        [
            "",
            "## Gap inventory",
            "",
            "| Host | Surface | Version | Capability | Mode | Gaps / workaround | OQ |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in rows:
        gaps = "; ".join(row["known_gaps"]) if row["known_gaps"] else "—"
        oq = ",".join(row["oq_flags"]) if row["oq_flags"] else "—"
        # Codex:desktop called out per OQ-2 even when only soft gaps exist.
        flag_note = row["workaround_or_timeline"]
        if row["host"] == "codex" and row["surface"] == "desktop":
            flag_note = f"OQ-2: {flag_note}"
        lines.append(
            f"| {row['host']} | {row['surface']} | {row['version']} | "
            f"{row['capability']} | {row['implementation_mode']} | {gaps} / {flag_note} | {oq} |"
        )
    lines.append("")
    return "\n".join(lines)


def generate(
    records_dir: Path,
    *,
    fmt: str = "markdown",
) -> str:
    cells = build_matrix(load_records(records_dir))
    if fmt == "json":
        return json.dumps(matrix_to_json(cells), indent=2, sort_keys=True) + "\n"
    if fmt == "markdown":
        return matrix_to_markdown(cells)
    raise MatrixGeneratorError(f"unsupported format: {fmt}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate platform support matrix from tested conformance records (PRD 349)."
    )
    parser.add_argument(
        "--records",
        type=Path,
        default=None,
        help="Directory of conformance record JSON files (default: core/schemas/capabilities/conformance)",
    )
    parser.add_argument(
        "--format",
        choices=("markdown", "json"),
        default="markdown",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path (default: stdout)",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository root for default records path",
    )
    parser.add_argument(
        "--known-gaps-out",
        type=Path,
        default=None,
        help="Also write known-gaps markdown derived from capability descriptors",
    )
    parser.add_argument(
        "--descriptors",
        type=Path,
        default=None,
        help="Capability descriptor directory (default: core/schemas/capabilities)",
    )
    args = parser.parse_args(list(sys.argv[1:] if argv is None else argv))
    repo_root = args.repo_root or Path(__file__).resolve().parents[1]
    records_dir = args.records or default_records_dir(repo_root)
    try:
        payload = generate(records_dir, fmt=args.format)
    except MatrixGeneratorError as exc:
        print(f"matrix_generator: {exc}", file=sys.stderr)
        return 1
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(payload, encoding="utf-8")
    else:
        sys.stdout.write(payload)
    if args.known_gaps_out:
        descriptors = args.descriptors or default_descriptors_dir(repo_root)
        gaps_md = known_gaps_to_markdown(collect_known_gaps(descriptors))
        args.known_gaps_out.parent.mkdir(parents=True, exist_ok=True)
        args.known_gaps_out.write_text(gaps_md, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
