"""Greenfield init smoke for scripts façade (PRD 073 phase 6 / R1, R3, R13, R16)."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

from init_scripts_facade import (
    DELIVER_ENTRYPOINTS,
    FORWARDER_SCRIPTS,
    emit_facade,
    manifest_path,
    probe_deliver_entrypoints,
    should_emit_facade,
)
from sw_scripts_resolve import (
    CONSUMER_NO_PLUGIN_ERROR,
    resolve_script,
    resolve_scripts_dir,
    scripts_dir_is_trusted,
)


def _seed_plugin_scripts(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    for name in FORWARDER_SCRIPTS:
        (path / name).write_text(f"# stub {name}\nif __name__ == '__main__': pass\n", encoding="utf-8")


def _seed_consumer(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    (root / ".cursor").mkdir(exist_ok=True)
    (root / ".cursor" / "workflow.config.json").write_text(
        json.dumps({"version": 1, "memory": {"provider": "in-repo"}}) + "\n",
        encoding="utf-8",
    )


def test_should_not_emit_in_shipwright_self_repo(repo_root: Path) -> None:
    assert not should_emit_facade(repo_root)
    payload = emit_facade(repo_root)
    assert payload["verdict"] == "skip"


def test_emit_writes_dispatcher_and_forwarders(tmp_path: Path) -> None:
    consumer = tmp_path / "consumer"
    plugin = tmp_path / "plugin"
    _seed_consumer(consumer)
    _seed_plugin_scripts(plugin)

    payload = emit_facade(consumer, plugin_scripts=plugin)
    assert payload["verdict"] == "pass"

    dispatcher = consumer / "scripts" / "sw"
    assert dispatcher.is_file()
    assert not dispatcher.is_symlink()
    assert dispatcher.stat().st_mode & 0o111

    for name in FORWARDER_SCRIPTS:
        forwarder = consumer / "scripts" / name
        assert forwarder.is_file(), name
        assert not forwarder.is_symlink(), name
        assert "generated by /sw-init" in forwarder.read_text(encoding="utf-8")

    manifest = json.loads(manifest_path(consumer).read_text(encoding="utf-8"))
    assert manifest["pluginScripts"] == str(plugin.resolve())
    assert manifest["deliverEntrypoints"] == list(DELIVER_ENTRYPOINTS)


def test_greenfield_probe_fails_closed_without_plugin(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    consumer = tmp_path / "consumer"
    plugin = tmp_path / "plugin"
    _seed_consumer(consumer)
    _seed_plugin_scripts(plugin)
    emit_facade(consumer, plugin_scripts=plugin)

    scripts = consumer / "scripts"
    assert scripts_dir_is_trusted(scripts)
    monkeypatch.delenv("SHIPWRIGHT_SCRIPTS", raising=False)
    monkeypatch.setattr("sw_scripts_resolve.PLUGIN_LOCAL_SCRIPTS", tmp_path / "missing-plugin")
    monkeypatch.setattr("sw_scripts_resolve.PLUGIN_CACHE_ROOT", tmp_path / "missing-cache")
    result = resolve_scripts_dir(consumer)
    assert result.path is None
    assert result.error == CONSUMER_NO_PLUGIN_ERROR

    with pytest.raises(Exception, match="plugin not installed"):
        resolve_script(consumer, DELIVER_ENTRYPOINTS[0])

    probe = probe_deliver_entrypoints(consumer)
    assert probe["verdict"] == "fail"
    assert probe["resolveErrors"]


def test_cli_probe_subcommand(tmp_path: Path) -> None:
    consumer = tmp_path / "consumer"
    plugin = tmp_path / "plugin"
    _seed_consumer(consumer)
    _seed_plugin_scripts(plugin)
    emit_facade(consumer, plugin_scripts=plugin)

    proc = subprocess.run(
        [sys.executable, str(Path(__file__).resolve().parents[2] / "init_scripts_facade.py"), str(consumer), "probe"],
        cwd=str(consumer),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr
    payload = json.loads(proc.stdout)
    assert payload["verdict"] == "pass"


def test_emit_fails_when_plugin_targets_missing(tmp_path: Path) -> None:
    consumer = tmp_path / "consumer"
    plugin = tmp_path / "plugin"
    _seed_consumer(consumer)
    plugin.mkdir()
    (plugin / "check-gate.py").write_text("# only marker\n", encoding="utf-8")
    (plugin / "resolve-model-tier.py").write_text("# only marker\n", encoding="utf-8")

    payload = emit_facade(consumer, plugin_scripts=plugin)
    assert payload["verdict"] == "fail"
    assert payload["missing"]
