#!/usr/bin/env python3
"""Regenerate CI workflows from suite-registry plans and pr-test-plan manifest (PRD 082 R35)."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from _sw.cli import run_module_main
from ci_shard_lib import group_fixtures_for_ci

MANIFEST_REL = Path("core/sw-reference/pr-test-plan.manifest.json")
PR_WORKFLOW_REL = Path(".github/workflows/pr-test-plan-ci.yml")
CI_WORKFLOW_REL = Path(".github/workflows/ci.yml")
GENERATOR_BANNER = "# Generated by scripts/ci_plan_gen.py — do not edit by hand."
MINIMUM_PYTHON = "3.10"
DEFAULT_PYTHON = "3.12"


def repo_root(start: Path | None = None) -> Path:
    start = start or SCRIPT_DIR
    cur = start.resolve()
    for candidate in (cur, *cur.parents):
        if (candidate / ".git").exists():
            return candidate
    return cur


def _relative_source(root: Path, path: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def suite_run_command(entry: dict[str, Any]) -> str:
    script = str(entry.get("script") or "")
    args = entry.get("args") or []
    if script.endswith((".py", ".test")):
        runner = "python3"
    else:
        runner = "bash"
    suffix = " " + " ".join(str(a) for a in args) if args else ""
    return f"{runner} {script}{suffix}"


def _python_setup_steps(python_version: str) -> list[str]:
    return [
        "      - uses: actions/checkout@v4",
        "      - uses: actions/setup-python@v5",
        "        with:",
        f'          python-version: "{python_version}"',
    ]


def generate_pr_test_plan_workflow(
    root: Path,
    *,
    manifest_path: Path | None = None,
    out_path: Path | None = None,
) -> str:
    manifest_path = manifest_path or (root / MANIFEST_REL)
    out_path = out_path or (root / PR_WORKFLOW_REL)
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    fixtures = data.get("fixtures") or []
    jobs = group_fixtures_for_ci(fixtures)

    lines = [
        GENERATOR_BANNER,
        f"# Source: {_relative_source(root, manifest_path)}",
        "name: PR test-plan (FEAT)",
        "",
        "on:",
        "  pull_request:",
        "",
        "permissions:",
        "  contents: read",
        "",
        "jobs:",
    ]

    for job in jobs:
        job_id = job["ciJobName"]
        classification = job.get("classification", "required")
        lines.append(f"  {job_id}:")
        lines.append(f"    name: {job_id}")
        lines.append("    runs-on: ubuntu-latest")
        if classification == "advisory":
            lines.append("    continue-on-error: true")
        lines.append("    steps:")
        lines.extend(_python_setup_steps(DEFAULT_PYTHON))
        suite_ids = job.get("suiteIds") or [entry["id"] for entry in job.get("entries") or []]
        label = ", ".join(suite_ids) if len(suite_ids) > 1 else str(suite_ids[0])
        lines.append(f"      - name: Run {label}")
        lines.append(f"        run: {job['command']}")
        lines.append("")

    text = "\n".join(lines) + "\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return text


def _ci_yml_fixture_steps(registry: dict[str, Any]) -> list[tuple[str, str]]:
    steps: list[tuple[str, str]] = []
    for row in registry.get("suites") or []:
        if "ci-yml" not in (row.get("lanes") or []):
            continue
        pytest_path = row.get("pytestPath")
        if not pytest_path:
            continue
        steps.append((str(row["id"]), f"python3 scripts/test/run_pytest.py {pytest_path} -q"))
    return steps


def _minimum_python_plan_commands(registry: dict[str, Any]) -> list[tuple[str, str]]:
    import test_scope as ts

    plan = ts.resolve_named_plan("minimum-python", [], registry=registry)
    by_id = {row["id"]: row for row in registry.get("suites") or []}
    commands: list[tuple[str, str]] = []
    for suite_id in plan.get("suites") or []:
        row = by_id.get(str(suite_id))
        if not isinstance(row, dict):
            continue
        commands.append((str(suite_id), suite_run_command(row)))
    return commands


def generate_ci_workflow(root: Path, *, out_path: Path | None = None) -> str:
    import suite_registry as sr

    registry = sr.load_registry(root)
    out_path = out_path or (root / CI_WORKFLOW_REL)
    fixture_steps = _ci_yml_fixture_steps(registry)
    minimum_steps = _minimum_python_plan_commands(registry)

    lines = [
        GENERATOR_BANNER,
        f"# Source: {_relative_source(root, root / sr.REGISTRY_REL)}",
        "name: CI",
        "",
        "on:",
        "  pull_request:",
        "  push:",
        "    branches:",
        "      - main",
        "  schedule:",
        '    - cron: "0 6 * * *"',
        "",
        "permissions:",
        "  contents: read",
        "",
        "jobs:",
        "  fixtures:",
        "    name: fixtures",
        "    if: github.event_name == 'pull_request'",
        "    runs-on: ubuntu-latest",
        "    steps:",
    ]
    lines.extend(_python_setup_steps(DEFAULT_PYTHON))
    for step_id, command in fixture_steps:
        lines.append(f"      - name: {step_id}")
        lines.append(f"        run: {command}")
        lines.append("")

    lines.extend(
        [
            "  verify-main-full:",
            "    name: verify-main-full",
            "    if: github.event_name == 'push' && github.ref == 'refs/heads/main'",
            "    runs-on: ubuntu-latest",
            "    steps:",
        ]
    )
    lines.extend(_python_setup_steps(DEFAULT_PYTHON))
    lines.extend(
        [
            "      - name: Named plan main-full",
            "        run: PYTHONPATH=scripts python3 scripts/test/_runner.py verify --scope full",
            "",
            "  verify-scheduled-full-plus-integration:",
            "    name: verify-scheduled-full-plus-integration",
            "    if: github.event_name == 'schedule'",
            "    runs-on: ubuntu-latest",
            "    steps:",
        ]
    )
    lines.extend(_python_setup_steps(DEFAULT_PYTHON))
    lines.extend(
        [
            "      - name: Named plan scheduled-full-plus-integration",
            "        run: PYTHONPATH=scripts python3 scripts/test/_runner.py run-pytest --scope full scripts/unit_tests",
            "",
            "  minimum-python:",
            "    name: minimum-python",
            "    runs-on: ubuntu-latest",
            "    strategy:",
            "      matrix:",
            f"        python-version: [\"{MINIMUM_PYTHON}\"]",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: actions/setup-python@v5",
            "        with:",
            '          python-version: "${{ matrix.python-version }}"',
            "      - name: Vendored pytest bootstrap",
            "        run: python3 scripts/test/run_pytest.py --version",
        ]
    )
    for step_id, command in minimum_steps:
        lines.append(f"      - name: minimum-python {step_id}")
        lines.append(f"        run: {command}")
        lines.append("")

    text = "\n".join(lines) + "\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return text


def generate_all(root: Path) -> tuple[str, str]:
    pr_text = generate_pr_test_plan_workflow(root)
    ci_text = generate_ci_workflow(root)
    return pr_text, ci_text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate CI workflows from registry plans.")
    parser.add_argument(
        "target",
        nargs="?",
        choices=("all", "pr-test-plan", "ci"),
        default="all",
        help="Workflow target (default: all)",
    )
    parser.add_argument("manifest", nargs="?", help="pr-test-plan manifest path")
    parser.add_argument("out", nargs="?", help="Output workflow path")
    parser.add_argument("root", nargs="?", help="Repository root")
    ns = parser.parse_args(argv)

    root = Path(ns.root) if ns.root else repo_root()
    if ns.target == "pr-test-plan":
        manifest = Path(ns.manifest) if ns.manifest else root / MANIFEST_REL
        out = Path(ns.out) if ns.out else root / PR_WORKFLOW_REL
        generate_pr_test_plan_workflow(root, manifest_path=manifest, out_path=out)
        print(f"Wrote {out}")
        return 0
    if ns.target == "ci":
        out = Path(ns.out) if ns.out else root / CI_WORKFLOW_REL
        generate_ci_workflow(root, out_path=out)
        print(f"Wrote {out}")
        return 0

    pr_path, ci_path = root / PR_WORKFLOW_REL, root / CI_WORKFLOW_REL
    generate_all(root)
    print(f"Wrote {pr_path} and {ci_path}")
    return 0


if __name__ == "__main__":
    run_module_main(main)
