#!/usr/bin/env python3
"""Consumer scripts façade helpers — emit retired (PRD 078 R1/R2).

Consumer repos use zero-footprint resolution via ``sw_bootstrap.py`` and the plugin
install. Legacy façade detection, probe, and confirm-gated removal helpers remain for
migration; ``emit`` is a no-op that never writes repo-local Shipwright scripts.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import subprocess
import sys
from pathlib import Path
from typing import Any, Literal

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from _sw.cli import run_module_main
from sw_scripts_resolve import (
    TRUST_MARKERS,
    is_shipwright_self_repo,
    plugin_install_scripts,
    resolve_script,
    resolve_scripts_dir,
    scripts_dir_is_trusted,
)

MANIFEST_REL = ".cursor/sw-scripts-facade.json"

# Documented deliver entrypoint forwarders — extend only via /sw-init re-emit.
DELIVER_ENTRYPOINTS: tuple[str, ...] = (
    "wave.py",
    "wave_deliver.py",
    "wave_deliver_loop.py",
    "wave_lifecycle.py",
    "wave_merge.py",
    "wave_preflight.py",
)

FORWARDER_SCRIPTS: tuple[str, ...] = tuple(
    dict.fromkeys((*DELIVER_ENTRYPOINTS, *TRUST_MARKERS))
)

SW_DISPATCHER = """#!/usr/bin/env bash
# Shipwright scripts dispatcher — generated by /sw-init; do not edit manually.
set -euo pipefail
if [[ $# -lt 1 ]]; then
  echo "usage: scripts/sw <script-name> [args...]" >&2
  exit 2
fi
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$1"
shift
TARGET="$REPO_ROOT/scripts/$SCRIPT"
if [[ ! -f "$TARGET" ]]; then
  echo "missing forwarder: $TARGET" >&2
  exit 2
fi
exec python3 "$TARGET" "$@"
"""

FORWARDER_HEADER_MARKER = "Shipwright script forwarder — generated by /sw-init"
DISPATCHER_HEADER_MARKER = "Shipwright scripts dispatcher — generated by /sw-init"
MANIFEST_GENERATED_BY = "init_scripts_facade"

FORWARDER_BODY = '''#!/usr/bin/env python3
"""Shipwright script forwarder — generated by /sw-init; do not edit manually."""
from __future__ import annotations

import json
import runpy
import sys
from pathlib import Path

_MANIFEST = ".cursor/sw-scripts-facade.json"
_SELF = Path(__file__).resolve().name


def _plugin_target() -> Path:
    repo = Path(__file__).resolve().parent.parent
    manifest_path = repo / _MANIFEST
    if not manifest_path.is_file():
        raise SystemExit(f"missing facade manifest: {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    plugin = Path(str(manifest.get("pluginScripts") or ""))
    if not plugin.is_dir():
        raise SystemExit(f"invalid pluginScripts in facade manifest: {plugin}")
    target = plugin / _SELF
    if not target.is_file():
        raise SystemExit(f"plugin script missing: {target}")
    return target


if __name__ == "__main__":
    target = _plugin_target()
    sys.argv[0] = str(target)
    runpy.run_path(str(target), run_name="__main__")
'''


def shipwright_version(root: Path) -> str:
    for candidate in (root / "version.txt", Path.home() / ".cursor/plugins/local/shipwright/version.txt"):
        if candidate.is_file():
            return candidate.read_text(encoding="utf-8").strip()
    return "unknown"


def resolve_emit_plugin_scripts(root: Path, override: Path | None = None) -> Path:
    if override is not None:
        candidate = override.resolve()
        if not scripts_dir_is_trusted(candidate):
            raise ValueError(f"override is not a trusted scripts root: {candidate}")
        return candidate
    if is_shipwright_self_repo(root):
        return (root / "scripts").resolve()
    plugin = plugin_install_scripts()
    if plugin is not None:
        return plugin
    env_raw = os.environ.get("SHIPWRIGHT_SCRIPTS", "").strip()
    if env_raw:
        from sw_scripts_resolve import validate_env_scripts_root

        env_path, env_err = validate_env_scripts_root(env_raw)
        if env_err:
            raise ValueError(env_err)
        if env_path is not None:
            return env_path
    raise ValueError(
        "no trusted plugin scripts root; install Shipwright locally or set SHIPWRIGHT_SCRIPTS"
    )


def manifest_path(root: Path) -> Path:
    return root / MANIFEST_REL


def load_manifest(root: Path) -> dict[str, Any]:
    path = manifest_path(root)
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def should_emit_facade(root: Path) -> bool:
    """Consumer façade emit is retired; always False (PRD 078 R1/R2)."""
    _ = root
    return False


def _write_executable(path: Path, content: str, *, executable: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content if content.endswith("\n") else content + "\n", encoding="utf-8")
    mode = path.stat().st_mode
    if executable:
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    else:
        path.chmod((mode | stat.S_IWUSR) & ~stat.S_IXUSR & ~stat.S_IXGRP & ~stat.S_IXOTH)


def emit_facade(
    root: Path,
    *,
    plugin_scripts: Path | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Retired emit path — never writes consumer façade files (PRD 078 R1/R2)."""
    _ = plugin_scripts, dry_run
    root = root.resolve()
    if is_shipwright_self_repo(root):
        return {
            "verdict": "skip",
            "action": "emit-facade",
            "reason": "shipwright-self-repo",
        }
    return {
        "verdict": "skip",
        "action": "emit-facade",
        "reason": "emit-retired",
        "message": (
            "consumer façade emit retired; resolve helpers via sw_bootstrap.py "
            "or the installed Shipwright plugin"
        ),
    }


def _content_sha256(content: str) -> str:
    normalized = content if content.endswith("\n") else content + "\n"
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def _expected_forwarder_checksum() -> str:
    return _content_sha256(FORWARDER_BODY)


def _expected_dispatcher_checksum() -> str:
    return _content_sha256(SW_DISPATCHER)


def _manifest_is_legacy(manifest: dict[str, Any]) -> bool:
    return manifest.get("generatedBy") == MANIFEST_GENERATED_BY


def _read_text(path: Path) -> str | None:
    if not path.is_file():
        return None
    return path.read_text(encoding="utf-8")


def _classify_script_path(
    rel: str,
    path: Path,
    *,
    manifest: dict[str, Any],
) -> dict[str, Any]:
    content = _read_text(path)
    if content is None:
        return {"path": rel, "identity": "absent"}

    manifest_forwarders = {
        str(name) for name in (manifest.get("forwarders") or []) if isinstance(name, str)
    }
    name = path.name
    header_match = False
    checksum_match = False
    expected_checksum: str | None = None

    if rel == "scripts/sw":
        header_match = DISPATCHER_HEADER_MARKER in content
        expected_checksum = _expected_dispatcher_checksum()
        checksum_match = _content_sha256(content) == expected_checksum
    elif name in FORWARDER_SCRIPTS or rel in manifest_forwarders:
        header_match = FORWARDER_HEADER_MARKER in content
        expected_checksum = _expected_forwarder_checksum()
        checksum_match = _content_sha256(content) == expected_checksum
    else:
        return {"path": rel, "identity": "foreign", "reason": "not-a-facade-candidate"}

    if header_match:
        return {
            "path": rel,
            "identity": "facade",
            "reason": "header",
            "corroboratedByChecksum": checksum_match,
        }
    if rel in manifest_forwarders and checksum_match:
        return {
            "path": rel,
            "identity": "facade",
            "reason": "manifest-and-checksum",
            "corroboratedByChecksum": True,
        }
    if rel in manifest_forwarders or name in FORWARDER_SCRIPTS or rel == "scripts/sw":
        return {
            "path": rel,
            "identity": "refused",
            "reason": "unmarked-facade-candidate",
        }
    return {"path": rel, "identity": "foreign", "reason": "not-a-facade-candidate"}


def _classify_manifest_path(_root: Path, manifest: dict[str, Any]) -> dict[str, Any]:
    rel = MANIFEST_REL
    if not manifest:
        return {"path": rel, "identity": "absent"}
    if _manifest_is_legacy(manifest):
        return {"path": rel, "identity": "facade", "reason": "manifest", "readOnly": True}
    return {"path": rel, "identity": "refused", "reason": "unknown-manifest"}


def _git_history_clobber(root: Path, rel: str) -> dict[str, Any] | None:
    if not (root / ".git").exists():
        return None
    proc = subprocess.run(
        [
            "git",
            "-C",
            str(root),
            "log",
            "--follow",
            "-n",
            "3",
            "--pretty=format:%H",
            "--",
            rel,
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0 or not proc.stdout.strip():
        return None
    commits = [line.strip() for line in proc.stdout.splitlines() if line.strip()]
    if len(commits) < 2:
        return None
    prior = commits[1]
    show = subprocess.run(
        ["git", "-C", str(root), "show", f"{prior}:{rel}"],
        capture_output=True,
        text=True,
        check=False,
    )
    if show.returncode != 0 or not show.stdout:
        return None
    prior_content = show.stdout
    if FORWARDER_HEADER_MARKER in prior_content or DISPATCHER_HEADER_MARKER in prior_content:
        return None
    return {
        "path": rel,
        "kind": "history-overwrite",
        "priorCommit": prior,
        "note": "git history shows a prior non-facade revision at this path; no restore offered",
    }


def detect_clobber(root: Path, entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Report façade clobber signals from content drift and git history (PRD 078 R8)."""
    root = root.resolve()
    clobber: list[dict[str, Any]] = []
    for entry in entries:
        if entry.get("identity") != "facade":
            continue
        rel = str(entry["path"])
        path = root / rel
        content = _read_text(path)
        if content is None:
            continue
        if rel == "scripts/sw":
            if _content_sha256(content) != _expected_dispatcher_checksum():
                clobber.append({
                    "path": rel,
                    "kind": "modified-template",
                    "note": "dispatcher content diverges from emitted template; no restore offered",
                })
        elif rel.startswith("scripts/"):
            if _content_sha256(content) != _expected_forwarder_checksum():
                clobber.append({
                    "path": rel,
                    "kind": "modified-template",
                    "note": "forwarder content diverges from emitted template; no restore offered",
                })
        history = _git_history_clobber(root, rel)
        if history is not None:
            clobber.append(history)
    return clobber


def detect_legacy_facade(root: Path) -> dict[str, Any]:
    """Detect residual consumer façade files and clobber signals (PRD 078 R8)."""
    root = root.resolve()
    if is_shipwright_self_repo(root):
        return {
            "verdict": "skip",
            "action": "detect-legacy-facade",
            "reason": "shipwright-self-repo",
        }

    manifest = load_manifest(root)
    entries: list[dict[str, Any]] = []
    entries.append(_classify_manifest_path(root, manifest))

    scripts_dir = root / "scripts"
    candidates = ["scripts/sw", *(f"scripts/{name}" for name in FORWARDER_SCRIPTS)]
    seen: set[str] = set()
    for rel in candidates:
        if rel in seen:
            continue
        seen.add(rel)
        entries.append(_classify_script_path(rel, root / rel, manifest=manifest))

    if scripts_dir.is_dir():
        for child in sorted(scripts_dir.iterdir()):
            rel = f"scripts/{child.name}"
            if rel in seen or not child.is_file():
                continue
            seen.add(rel)
            entries.append(_classify_script_path(rel, child, manifest=manifest))

    facade_files = [entry for entry in entries if entry.get("identity") == "facade"]
    refused = [entry for entry in entries if entry.get("identity") == "refused"]
    foreign = [entry for entry in entries if entry.get("identity") == "foreign"]
    clobber = detect_clobber(root, facade_files)

    if facade_files:
        verdict: Literal["found", "none"] = "found"
    else:
        verdict = "none"

    return {
        "verdict": verdict,
        "action": "detect-legacy-facade",
        "manifestPresent": bool(manifest),
        "manifestLegacy": _manifest_is_legacy(manifest) if manifest else False,
        "facadeFiles": facade_files,
        "refused": refused,
        "foreign": foreign,
        "clobber": clobber,
        "remediation": (
            "python3 scripts/init_scripts_facade.py . remove --confirm"
            if facade_files
            else None
        ),
    }


def remove_legacy_facade(root: Path, *, confirm: bool = False) -> dict[str, Any]:
    """Confirm-gated removal of identity-verified legacy façade files (PRD 078 R8)."""
    root = root.resolve()
    if is_shipwright_self_repo(root):
        return {
            "verdict": "skip",
            "action": "remove-legacy-facade",
            "reason": "shipwright-self-repo",
        }

    detection = detect_legacy_facade(root)
    if detection.get("verdict") == "skip":
        return detection

    to_remove = [entry["path"] for entry in detection.get("facadeFiles") or []]
    refused = detection.get("refused") or []
    if refused:
        return {
            "verdict": "fail",
            "action": "remove-legacy-facade",
            "error": "refused-unmarked-facade-candidates",
            "refused": refused,
            "facadeFiles": detection.get("facadeFiles") or [],
            "clobber": detection.get("clobber") or [],
        }

    if not to_remove:
        return {
            "verdict": "pass",
            "action": "remove-legacy-facade",
            "reason": "nothing-to-remove",
            "removed": [],
            "clobber": detection.get("clobber") or [],
        }

    if not confirm:
        return {
            "verdict": "pass",
            "action": "remove-legacy-facade",
            "dryRun": True,
            "wouldRemove": to_remove,
            "clobber": detection.get("clobber") or [],
            "remediation": "re-run with --confirm to delete identity-verified façade files",
        }

    removed: list[str] = []
    for rel in to_remove:
        path = root / rel
        if path.is_file():
            path.unlink()
            removed.append(rel)
        elif path.is_dir():
            continue
    scripts_dir = root / "scripts"
    if scripts_dir.is_dir() and not any(scripts_dir.iterdir()):
        scripts_dir.rmdir()

    return {
        "verdict": "pass",
        "action": "remove-legacy-facade",
        "removed": removed,
        "clobber": detection.get("clobber") or [],
    }


def _resolution_uses_consumer_scripts(root: Path, resolved: Path) -> bool:
    consumer_scripts = (root / "scripts").resolve()
    if not consumer_scripts.is_dir():
        return False
    try:
        resolved.relative_to(consumer_scripts)
    except ValueError:
        return False
    return True


def probe_deliver_entrypoints(
    root: Path,
    *,
    env: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Zero-footprint probe: no façade files; deliver entrypoints resolve via plugin/bootstrap."""
    root = root.resolve()
    if is_shipwright_self_repo(root):
        return {
            "verdict": "skip",
            "action": "probe-deliver-entrypoints",
            "reason": "shipwright-self-repo",
        }

    detection = detect_legacy_facade(root)
    facade_files = list(detection.get("facadeFiles") or [])
    refused = list(detection.get("refused") or [])
    errors: list[str] = []
    if facade_files:
        errors.append("residual-facade-files")
    if refused:
        errors.append("hand-forwarder-pollution")

    resolve_errors: list[str] = []
    resolved_sources: dict[str, str] = {}
    dir_result = resolve_scripts_dir(root, env=env, executor=Path(__file__))
    scripts_root_source = dir_result.source

    if dir_result.error:
        resolve_errors.append(f"scripts-root: {dir_result.error}")
    elif dir_result.path is None:
        resolve_errors.append("scripts-root: no trusted scripts root found")
    elif dir_result.source == "consumer":
        errors.append("resolution-needs-consumer-files")
    else:
        for name in DELIVER_ENTRYPOINTS:
            try:
                resolved = resolve_script(root, name, env=env, executor=Path(__file__))
            except Exception as exc:  # noqa: BLE001 — aggregate probe failures
                resolve_errors.append(f"{name}: {exc}")
                continue
            if _resolution_uses_consumer_scripts(root, resolved):
                errors.append(f"resolution-needs-consumer-files:{name}")
            else:
                resolved_sources[name] = scripts_root_source or "unknown"

    ok = not errors and not resolve_errors
    return {
        "verdict": "pass" if ok else "fail",
        "action": "probe-deliver-entrypoints",
        "mode": "zero-footprint",
        "facadeFiles": facade_files,
        "refused": refused,
        "errors": errors,
        "resolveErrors": resolve_errors,
        "resolvedSources": resolved_sources,
        "scriptsRootSource": scripts_root_source,
    }


def cmd_emit(root: Path, args: list[str]) -> int:
    dry_run = "--dry-run" in args
    override = None
    if "--plugin-scripts" in args:
        idx = args.index("--plugin-scripts")
        if idx + 1 < len(args):
            override = Path(args[idx + 1])
    try:
        payload = emit_facade(root, plugin_scripts=override, dry_run=dry_run)
    except ValueError as exc:
        print(json.dumps({"verdict": "fail", "action": "emit-facade", "error": str(exc)}, indent=2))
        return 2
    print(json.dumps(payload, indent=2))
    return 0 if payload.get("verdict") in ("pass", "skip") else 2


def cmd_probe(root: Path, _args: list[str]) -> int:
    payload = probe_deliver_entrypoints(root)
    print(json.dumps(payload, indent=2))
    return 0 if payload.get("verdict") == "pass" else 2


def cmd_detect(root: Path, _args: list[str]) -> int:
    payload = detect_legacy_facade(root)
    print(json.dumps(payload, indent=2))
    return 0 if payload.get("verdict") in ("found", "none", "skip") else 2


def cmd_remove(root: Path, args: list[str]) -> int:
    payload = remove_legacy_facade(root, confirm="--confirm" in args)
    print(json.dumps(payload, indent=2))
    if payload.get("verdict") == "fail":
        return 2
    return 0 if payload.get("verdict") in ("pass", "skip") else 2


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Emit / probe consumer scripts façade")
    parser.add_argument("root", type=Path, nargs="?", default=Path.cwd())
    parser.add_argument(
        "command",
        choices=("emit", "probe", "detect", "remove"),
        nargs="?",
        default="emit",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--confirm", action="store_true")
    parser.add_argument("--plugin-scripts", type=Path, default=None)
    args = parser.parse_args(argv)
    root = args.root.resolve()
    if args.command == "probe":
        return cmd_probe(root, [])
    if args.command == "detect":
        return cmd_detect(root, [])
    if args.command == "remove":
        return cmd_remove(root, ["--confirm"] if args.confirm else [])
    rest: list[str] = []
    if args.dry_run:
        rest.append("--dry-run")
    if args.plugin_scripts is not None:
        rest.extend(["--plugin-scripts", str(args.plugin_scripts)])
    return cmd_emit(root, rest)


if __name__ == "__main__":
    run_module_main(main)
