#!/usr/bin/env python3
"""Generated planning_store compatibility shim — re-exports the canonical module."""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any

# GENERATED BY planning_shim_gen.py — do not edit manually.
# Marker: planning-store-shim/v1

_CANONICAL_MODULE_NAME = "_planning_store_canonical"
_CANONICAL_REL = "scripts/planning_store_facade.py"
_REPO_ROOT_DEPTH = 2
_EXPORTED_NAMES = (
    'BITBUCKET_ISSUE_STORE_GUIDANCE',
    'DEFAULT_BACKEND',
    'DEFAULT_ISSUES_TOKEN_ENV',
    'DEFERRED_ISSUES_PROVIDERS',
    'FACADE_BYPASS_BASELINE',
    'FILE_BACKED_STORE_TXN_ID',
    'ISSUES_PROVIDERS',
    'InRepoPublicBackend',
    'IssueStoreBackend',
    'KILL_SWITCH_ENV',
    'KILL_SWITCH_NOTICE',
    'LocalSyncedBackend',
    'MATERIALIZE_MISSING_FROZEN_BODY',
    'MemoryLocalCacheBackend',
    'PROJECT_KEY_PATTERN',
    'PUT_INCOMPLETE_LABEL',
    'R1_BROWSE_CONTRACT',
    'SHIPPED_ISSUES_PROVIDERS',
    'SemanticStatusError',
    'StoreResult',
    '_ISSUES_PROVIDER_TO_BROKER',
    '_contains_raw_transcript',
    '_default_body_path',
    '_fail',
    '_gap_closure_evidence',
    '_github_scope_probe',
    '_is_allowed_recallium_base',
    '_issues_destination_endpoint',
    '_lookup_issue_record',
    '_parse_absorbs_targets',
    '_prd_number_from_unit_id',
    '_prd_unit_id_alias_candidates',
    '_redact_content',
    '_slug_from_prd_unit',
    '_store_section',
    '_tasks_unit_id_candidates',
    '_urlopen',
    'apply_initiative_capability',
    'assert_cycle_orthogonal_to_milestone',
    'assert_flat_comment_provider_non_regression',
    'assert_portable_graph_authority',
    'assert_projection_mirrors_not_freeze_authority',
    'assert_r1_answerability_from_metadata',
    'assert_r1_answerability_while_clean',
    'assign_issue_to_cycle',
    'audit_closure_completeness',
    'authority_io_block',
    'backfill_frontmatter_hybrid',
    'check_canonical_projection_split_brain',
    'check_projection_drift',
    'close_delivery_units',
    'close_done_phase_sub_issues',
    'close_parent_epic_if_complete',
    'comment_sync',
    'comments_relations_schema_contract',
    'contains_raw_transcript',
    'content_hash',
    'cycle_sharing_notice',
    'discover_absorbed_units_anchored',
    'doctor_absorb_linkage_066',
    'doctor_absorb_pollution',
    'doctor_issues_provider_stub',
    'doctor_separate_project_local_writes',
    'dual_write_body_policy',
    'dual_write_projection_mirror',
    'encode_planning_edge',
    'evaluate_freeze_gate',
    'fail',
    'format_native_unit_id',
    'freeze_from_canonical_body',
    'gap_has_absorb_provenance',
    'gate_prd_060_r1_r7',
    'get',
    'get_backend',
    'git_root',
    'is_bare_integer_unit_id',
    'is_namespaced_native_unit_id',
    'issue_comments_relations_facade',
    'issue_get_facade',
    'issue_index_key',
    'issue_search_by_unit_facade',
    'issue_store_fallback_reason',
    'issue_store_private_enough',
    'issue_store_visibility_allowed',
    'issue_store_visibility_gate',
    'issues_provider_registration_footprint',
    'issues_section',
    'linear_entity_mapping',
    'linear_projection_schema_contract',
    'lint_facade_imports',
    'lint_projection_mutations',
    'load_issue_unit_index',
    'load_projection_ledger',
    'load_put_journal',
    'load_workflow_config',
    'materialize_from_store',
    'materialize_with_resync',
    'migrate_orphan_phase_issues',
    'mutate_issue_unit_index',
    'normalize_semantic_status',
    'normalize_task_ref',
    'operator_projection_adapter_complete_claim',
    'operator_projection_capability_matrix',
    'operator_projection_contract',
    'override_path',
    'parse_planning_issues_refs',
    'parse_visibility_from_content',
    'planning_section',
    'probe_initiative_availability',
    'probe_issues_token',
    'probe_store_host_privacy',
    'progress_update',
    'project_graph_to_linear_layout',
    'projection_is_dirty',
    'projection_ledger_discover_by_marker',
    'projection_ledger_lookup',
    'projection_ledger_reconcile_duplicates',
    'projection_ledger_upsert',
    'ps',
    'put',
    'py',
    'read_issue_unit_index_locked',
    'rebuild_projection_from_graph',
    'reconcile_ledger_task_refs',
    'redact_content',
    'refuse_banned_living_doc_write',
    'register_legacy_unit_mapping',
    'reject_bare_integer_unit_id',
    'resolve_absorbed_gaps_061',
    'resolve_backend_id',
    'resolve_canonical_freeze_body',
    'resolve_delivery_linked_units',
    'resolve_effective_backend',
    'resolve_issues_credential',
    'resolve_issues_provider',
    'resolve_issues_token_env',
    'resolve_legacy_unit_id',
    'resolve_planning_issue_ref_to_gap',
    'resolve_store_location',
    'resolve_task_ref_aliases',
    'resume_projection_from_checkpoint',
    'reverse_resolve_legacy_unit_id',
    'save_issue_unit_index',
    'save_legacy_unit_map',
    'secret_scan_text',
    'serialize_comments_relations_facade',
    'set_projection_dirty',
    'store_section',
    'token_present',
    'validate_project_key',
    'verify_absorb_linkage_066',
    'wave_regression_finding',
    'write_back_gap_prereqs_061',
)
_cached: Any | None = None


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[_REPO_ROOT_DEPTH]


def _load_canonical():
    global _cached
    if _cached is not None:
        return _cached
    path = _repo_root() / _CANONICAL_REL
    spec = importlib.util.spec_from_file_location(_CANONICAL_MODULE_NAME, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load canonical planning store: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[_CANONICAL_MODULE_NAME] = module
    spec.loader.exec_module(module)
    _cached = module
    return module


def __getattr__(name: str) -> Any:
    return getattr(_load_canonical(), name)


def __dir__() -> list[str]:
    return sorted(set(dir(_load_canonical())) | set(globals()) | set(_EXPORTED_NAMES))


def main() -> None:
    _load_canonical().main()


if __name__ == "__main__":
    main()
